# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa31c9ff1962a4d35af1695d3fa19d3156127da97ada3cf006042863ab88314529076b88315c8efcbddfdc5c273168469b716345ef5e89cbba4ea47a10092e43

test:
  secret_key_base: 26aa4dd6473e9d82bace707b5f192befe4c006c2c46e04616390c23fd890d9b34f1909c73c5ed403dce9168b971b8389ded9bffdd188f7a8d3709b5f48732a18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
